### ISSUE TITLE
Request search devices

### ISSUE THREAD

**Issue by crystalcave** [EngstromJimmy/Blazm.Bluetooth#3]
Hello Jimmy, your project is precious! Thank you.
It would be nice to be able to manage the list of devices found and connect it from code.
This is not to avoid the basic rules of the bluetooth web (confirmation by the user), but to integrate the representation of the devices found on the page. Do you say it would be possible?

**Comment by EngstromJimmy** [comment]
Hi
Glad you like it.
As far as I understand (I double checked before replying) there is no way of doing that.
For security reasons, it is the web browser that lists and requests access to a device.

My guess is that it won't be available either since Apple has yet to implement the Web BLE standard due to security concerns.
I think that the coming iterations of the standard will be stricter.
