### ISSUE TITLE
Further implementations

### ISSUE THREAD

**Issue by davidwiki8** [EngstromJimmy/Blazm.Bluetooth#7]
Hi, will you continue adding new features from the Web Bluetooth API? 

For example, being able to read the MAC address of the device, reading all characteristics from a device or having also the device id on the notifications.

Thanks and nice job!

**Comment by davidwiki8** [comment]
I already found the answers I needed.

**Comment by EngstromJimmy** [comment]
To answer your question, I will continue to add features, I am however only doing this because I love gadgets so if there is a specific function you need please let me know and I can make it happen or you can ar a PR of course =)
It's always easier to have someone using the library identify the needs.
